---
services: docker

env:
  - distro: alpine:3.4
    init: su -c "/usr/bin/pg_ctl -- start -s -w -t 10 -l /var/log/postgresql/postgresql.log" postgres
    run_opts: ""
    postgresql_bin_path: /usr/bin
    postgresql_data_path: /var/lib/postgresql/data

services:
  - docker

before_install:
  # Pull container
  - docker pull alpine:3.4
  - docker build -t haterd/postgresql:latest tests/

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run -it -d --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} haterd/postgresql:latest "${init}" > "${container_id}"'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'

  # Test role.
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml'

  # Test role idempotence.
  - idempotence=$(mktemp)
  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Check PostgreSQL status.
  - 'docker exec -u postgres "$(cat ${container_id})" ${postgresql_bin_path}/pg_ctl -D ${postgresql_data_path} status'

after_failure:
  # Check what happened on postgresql.log .
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm gosu postgres tail -15 /var/log/postgresql/postgresql.log'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/