---
- name: Set PostgreSQL environment variables.
  template:
    src: postgres.sh.j2
    dest: /etc/profile.d/postgres
    mode: 0644

- name: Ensure PostgreSQL data directory exists.
  file:
    path: "{{ item }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700
  with_items:
    - "{{ postgresql_data_dir }}"
    - "{{ postgresql_data_dir | dirname }}"

- name: Ensure PostgreSQL log dirrectory exists.
  file:
    path: "{{ postgresql_log_path }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: Ensure PostgreSQL database is initialized.
  command: "{{ postgresql_handlers.init }}"
  when: not pgdata_dir_version.stat.exists
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true