---
# tasks file for postgresql

# Variable configuration.
- include: variables.yml

# Setup/install tasks.
- include: setup-Alpine.yml
  when: ansible_os_family == 'Alpine'

- include: initialize.yml
- include: configure.yml

- name: Check postgresql status
  command: "{{ postgresql_handlers.status }}"
  register: postgresql_status
  changed_when: False
  failed_when: postgresql_status.stdout.find("FAILED") != -1

- name: Start postgresql
  command: "{{ postgresql_handlers.start }}"
  when: postgresql_status.stdout.find("server is running") == -1

- name: Wait for postgres to be started
  command: "{{ postgresql_handlers.status }}"
  register: postgresql_started
  until: postgresql_started.stdout.find("server is running") != -1
  retries: 10
  delay: 10
  when: postgresql_status.stdout.find("server is running") == -1

# Configure PostgreSQL.
- include: databases.yml
- include: users.yml

