---
# tasks file for postgresql

# Variable configuration.
- include: variables.yml

# Setup/install tasks.
- include: setup-Alpine.yml
  when: ansible_os_family == 'Alpine'

- include: initialize.yml
- include: configure.yml

- block:
  - name: Check postgresql status
    debug:
      msg: "{{ lookup('pipe', 'gosu '+ postgresql_user+' '+postgresql_bin_path +'/pg_ctl -- status -D {{ postgresql_data_dir }}') }}"
    register: postgresql_status
    ignore_errors: True

  - name: Start postgresql
    command: 'gosu {{ postgresql_user }} {{ postgresql_bin_path }}/pg_ctl -- start -D {{ postgresql_data_dir }} -s -w -t 10 -l {{postgresql_log_path}}/postgresql.log'
    when: "'server is running' not in postgresql_status.msg"

  - name: Wait for postgres to be started
    debug:
      msg: "{{ lookup('pipe', 'gosu '+ postgresql_user+' '+postgresql_bin_path +'/pg_ctl -- status -D {{ postgresql_data_dir }}') }}"
    register: postgresql_started
    until: "'server is running' in postgresql_started.msg"
    retries: 10
    delay: 10
    when: "'server is running' not in postgresql_status.msg"

  when: ansible_os_family == 'Alpine'

# Configure PostgreSQL.
- include: databases.yml
- include: users.yml

