---
# tasks file for postgresql

# Variable configuration.
- include: variables.yml

# Setup/install tasks.
- include: setup-Alpine.yml
  when: ansible_os_family == 'Alpine'

- include: initialize.yml
- include: configure.yml

- block:
  - name: Check postgresql status
    shell: "/usr/local/bin/gosu {{ postgresql_user }} {{ postgresql_bin_path }}/pg_ctl -- status -D {{ postgresql_data_dir }}"
    register: postgresql_status
    ignore_errors: True

  - name: Start postgresql
    command: 'gosu {{ postgresql_user }} {{ postgresql_bin_path }}/pg_ctl -- start -D {{ postgresql_data_dir }} -s -w -t 10 -l {{postgresql_log_path}}/postgresql.log'
    when: postgresql_status.stdout.find("server is running") == -1

  - name: Wait for postgres to be started
    shell: "/usr/local/bin/gosu {{ postgresql_user }} {{ postgresql_bin_path }}/pg_ctl -- status -D {{ postgresql_data_dir }}"
    register: postgresql_started
    until: postgresql_started.stdout.find("server is running") != -1
    retries: 10
    delay: 10
    when: postgresql_status.stdout.find("server is running") == -1

  when: ansible_os_family == 'Alpine'

# Configure PostgreSQL.
- include: databases.yml
- include: users.yml

