---
# tasks file for postgresql

# Variable configuration.
- include: variables.yml

# Setup/install tasks.
- include: setup-Alpine.yml
  when: ansible_os_family == 'Alpine'

- include: initialize.yml
- include: configure.yml

- block:
  - name: Check postgresql status
    debug:
      msg: "{{ lookup('pipe', 'gosu'+' postgresql_user postgresql_bin_path +'/pg_ctl -- status') }}"
    register: postgresql_status
    ignore_errors: True

  - name: Start postgresql
    command: 'gosu {{ postgresql_user }} {{ postgresql_bin_path }}/pg_ctl -- start -s -w -t 10 -l {{postgresql_log_path}}/postgresql.log'
    when: "'server is running' not in postgresql_status.msg"
  when: ansible_os_family == 'Alpine'

# Configure PostgreSQL.
- include: databases.yml
- include: users.yml

