---

- name: Install builddeps
  command: apk --no-cache add --virtual postgres-build-deps python-dev ca-certificates openssl
  args:
    creates: /usr/local/bin/gosu
  register: gosu_installed

- name: Install gosu
  get_url:
    dest: /usr/local/bin/gosu
    url: https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64
    mode: 0774
    validate_certs: no

- name: Ensure PostgreSQL Python libraries are installed.
  command: apk --no-cache add py-psycopg2
  args:
    creates: /usr/lib/*/site-packages/psycopg2

- name: Ensure PostgreSQL packages are installed.
  command: "apk add --no-cache --update {{item}}={{postgresql_version}}"
  with_items: "{{ postgresql_packages }}"
  args:
    creates: "{{postgresql_bin_path}}/postgres"

#- name: Ensure all configured locales are present.
#  locale_gen: "name={{ item }} state=present"
#  with_items: "{{ postgresql_locales }}"
#  register: locale_gen_result

#- name: Force-restart PostgreSQL after new locales are generated.
#  service:
#    name: "{{ postgresql_daemon }}"
#    state: restarted
#  when: locale_gen_result.changed

- name: Remove builddeps
  command: apk del postgres-build-deps
  when: gosu_installed.changed